version: '3'

services:
  qna:
    build: .
    depends_on:
      - 'database'
    ports:
      - '4000:4000'

  database:
    image: mongo:latest

# yml for docker
# version: '3.1'

# services:
#   database:
#     image: mongo:latest

#   server:
#     image: cloverjoy/qna
#     depends_on:
#       - database
#     ports:
#       - 80:4000